# =====================================================================
# 07_balance_descriptives.R — Balance test + Table 1 + rollout diagnostics
#
# Inputs :  data/intermediate/stage06/analysis_sample.rds
#           data/intermediate/stage03/midwife_rollout.rds
#           data/intermediate/stage03/rollout_comparison.rds
#           data/intermediate/stage03/other_facilities.rds
#
# Outputs:  paper/tables/balance.tex
#           paper/tables/rollout_sar_vs_pkk.tex
#           paper/tables/table1_descriptives.tex
#           paper/figures/rollout_histogram.pdf
#
# Purpose: document the endogeneity of VM placement (the balance table
# is expected to reject random placement — this motivates the identi-
# fication stack), summarise the SAR vs PKK disagreement that the
# regression plan inherits, and produce the paper's Table 1.
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
  library(modelsummary)
  library(fixest)
})

# Use plain booktabs output rather than tabularray (one fewer
# dependency to drop into the paper preamble).
options(modelsummary_factory_latex = "kableExtra",
        modelsummary_format_numeric_latex = "plain")

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage07", "begin")

frame    <- read_intermediate("stage06", "analysis_sample")
rollout  <- read_intermediate("stage03", "midwife_rollout")
compare  <- read_intermediate("stage03", "rollout_comparison")
other_f  <- read_intermediate("stage03", "other_facilities")

tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------
# 1. Balance table on pre-treatment individual covariates.
#    Compare children in early-treated vs late-treated communities on
#    mother and child characteristics fixed at (or before) birth. If
#    placement were random, the two groups should be similar on these
#    pre-determined covariates.
#    Early / late split at the median SAR rollout year among treated
#    communities; non-migrants by the preceding-wave variant.
# ---------------------------------------------------------------------
bal_sample <- frame |>
  filter(primary_sample == 1,
         !is.na(start_sar_legacy)) |>
  mutate(
    early_village = as.integer(
      start_sar_legacy <=
        stats::median(start_sar_legacy, na.rm = TRUE))
  )

balance_rows <- tibble::tribble(
  ~varname,           ~label,
  "mother_edu_years", "Mother's education (years)",
  "mother_age_birth", "Mother's age at birth (years)",
  "mother_height",    "Mother's height (cm)",
  "female",           "Female"
) |>
  mutate(female = NA_integer_)  # placeholder; `female` built inline

# Build the `female` column once and bind to bal_sample.
bal_sample$female <- as.integer(bal_sample$sex == 3)

balance_tbl <- lapply(
  c("mother_edu_years", "mother_age_birth", "mother_height", "female"),
  function(v) {
    a <- bal_sample[[v]][bal_sample$early_village == 1]
    b <- bal_sample[[v]][bal_sample$early_village == 0]
    tt <- tryCatch(stats::t.test(a, b), error = function(e) NULL)
    tibble::tibble(
      Variable   = v,
      Early_mean = mean(a, na.rm = TRUE),
      Late_mean  = mean(b, na.rm = TRUE),
      Difference = mean(a, na.rm = TRUE) - mean(b, na.rm = TRUE),
      p_value    = if (!is.null(tt)) tt$p.value else NA_real_,
      N_early    = sum(!is.na(a)),
      N_late     = sum(!is.na(b))
    )
  }) |> bind_rows()

pretty_var <- c(
  mother_edu_years = "Mother's education (years)",
  mother_age_birth = "Mother's age at birth (years)",
  mother_height    = "Mother's height (cm)",
  female           = "Female"
)
balance_tbl$label <- pretty_var[balance_tbl$Variable]

# Stars on difference p-values.
stars <- ifelse(is.na(balance_tbl$p_value), "",
         ifelse(balance_tbl$p_value < 0.01, "$^{***}$",
         ifelse(balance_tbl$p_value < 0.05, "$^{**}$",
         ifelse(balance_tbl$p_value < 0.10, "$^{*}$", ""))))

writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lrrrr}",
  "\\toprule",
  "Variable & Early-rollout mean & Late-rollout mean & Difference & $p$-value \\\\",
  "\\midrule",
  vapply(seq_len(nrow(balance_tbl)), function(i) sprintf(
    "%s & %.3f & %.3f & %.3f%s & %.3f \\\\",
    balance_tbl$label[i],
    balance_tbl$Early_mean[i],
    balance_tbl$Late_mean[i],
    balance_tbl$Difference[i],
    stars[i],
    balance_tbl$p_value[i]
  ), character(1)),
  "\\midrule",
  sprintf("$N$ (children) & \\multicolumn{2}{c}{%s / %s} & & \\\\",
          format(balance_tbl$N_early[1], big.mark = ","),
          format(balance_tbl$N_late[1], big.mark = ",")),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "balance.tex"))

log_stage("stage07", sprintf(
  "balance table: %d covariates (early vs late-treated villages).",
  nrow(balance_tbl)))

# ---------------------------------------------------------------------
# 2. SAR vs PKK rollout diagnostic table.
# ---------------------------------------------------------------------
both <- compare |> filter(has_both == 1)
rc <- tibble::tibble(
  Metric = c("Communities total",
             "With SAR start-year",
             "With PKK start-year",
             "With both",
             "Pearson rho(SAR, PKK)",
             "Share disagreeing (both present)",
             "Mean |SAR - PKK| (years)"),
  Value  = c(nrow(compare),
             sum(compare$has_sar),
             sum(compare$has_pkk),
             nrow(both),
             if (nrow(both) > 3)
               round(cor(both$start_year_sar,
                         both$start_year_pkk, use = "complete.obs"), 3)
             else NA_real_,
             round(mean(both$start_year_sar != both$start_year_pkk), 3),
             round(mean(abs(both$delta), na.rm = TRUE), 2))
)

writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lr}",
  "\\toprule",
  "Metric & Value \\\\",
  "\\midrule",
  apply(rc, 1, function(r) sprintf("%s & %s \\\\",
                                   r["Metric"], r["Value"])),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "rollout_sar_vs_pkk.tex"))

log_stage("stage07", sprintf(
  "rollout diagnostic: %d commids with both; rho=%.3f; disagree=%.3f",
  nrow(both), rc$Value[5], rc$Value[6]))

# ---------------------------------------------------------------------
# 3. Table 1 — descriptive statistics on the primary sample.
# ---------------------------------------------------------------------
# Row formatter: integer-valued variables get integer Min/Median/Max;
# continuous variables get one decimal (or two for small values).
# Mean and SD are always 3 decimals.
format_summary_row <- function(v, name) {
  v <- v[!is.na(v)]
  n  <- length(v)
  if (n == 0) {
    return(sprintf("%s & 0 & --- & --- & --- & --- & --- \\\\", name))
  }
  m  <- mean(v)
  sd <- stats::sd(v)
  mn <- min(v)
  md <- stats::median(v)
  mx <- max(v)
  is_int <- isTRUE(all(v == round(v)))
  fmt_extreme <- function(x) {
    if (is_int) sprintf("%d", as.integer(x))
    else if (abs(x) >= 100) sprintf("%.1f", x)
    else sprintf("%.2f", x)
  }
  sprintf("%s & %s & %.3f & %.3f & %s & %s & %s \\\\",
          name, format(n, big.mark = ","), m, sd,
          fmt_extreme(mn), fmt_extreme(md), fmt_extreme(mx))
}

# Build the primary-sample frame with the variables for the summary
# table. Sex IFLS roster ar07: 1 = male, 3 = female.
# Province (Java or Bali) covers BPS province codes 31--35 (DKI, West
# Java, Central Java, Yogyakarta, East Java) and 51 (Bali).
prim <- frame |>
  dplyr::filter(primary_sample == 1) |>
  dplyr::mutate(
    Female                         = as.integer(sex == 3),
    `Age in 2014`                  = 2014 - birth_year,
    `Province (Java or Bali)`      = as.integer(province %in% c(31, 32, 33, 34, 35, 51)),
    `Mother's age at birth`        = mother_age_birth,
    `Mother's years of schooling`  = mother_edu_years,
    `Mother's height (cm)`         = mother_height
  )

# Panel B is at the community level (one row per commid_birth_legacy):
# treated = community has any village-midwife rollout year on record.
# Start year is observed only for treated communities.
comm_panel <- prim |>
  dplyr::distinct(commid_birth_legacy, .keep_all = TRUE) |>
  dplyr::transmute(
    `Treated community`          = as.integer(!is.na(start_sar_legacy)),
    `Village midwife start year` = start_sar_legacy
  )

panelA_vars <- c("Female", "Age in 2014", "Province (Java or Bali)",
                 "Mother's age at birth", "Mother's years of schooling",
                 "Mother's height (cm)")
panelB_vars <- c("Treated community", "Village midwife start year")

panelA_rows <- vapply(panelA_vars,
                      function(v) format_summary_row(prim[[v]], v),
                      character(1))
panelB_rows <- vapply(panelB_vars,
                      function(v) format_summary_row(comm_panel[[v]], v),
                      character(1))

tex_lines <- c(
  "\\begin{table}[!htbp]",
  "\\centering",
  "\\caption{Summary statistics.}\\label{tab:descriptives}",
  "\\begin{tabular}{lrrrrrr}",
  "\\toprule",
  "Variable & N & Mean & SD & Min & Median & Max \\\\",
  "\\midrule",
  "\\multicolumn{7}{l}{\\emph{Panel A: Individual and family characteristics}} \\\\",
  panelA_rows,
  "\\midrule",
  "\\multicolumn{7}{l}{\\emph{Panel B: Program exposure (community of birth)}} \\\\",
  panelB_rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\begin{minipage}{0.9\\textwidth}",
  "\\footnotesize",
  "\\emph{Notes.} Sample: non-migrant children born 1984--1999. Panel A reports individual and family characteristics across all primary-sample individuals. Panel B reports program exposure at the community of birth: rows are at the community level, with the treated indicator equal to one if the village midwife is ever recorded in either the SAR or the PKK rollout source, and the start-year row defined only for treated communities.",
  "\\end{minipage}",
  "\\end{table}"
)

tex_path <- file.path(tables_dir, "table1_descriptives.tex")
writeLines(tex_lines, tex_path)

log_stage("stage07", sprintf(
  "Table 1 written: N=%d primary individuals; communities=%d (treated=%d, untreated=%d).",
  nrow(prim), nrow(comm_panel),
  sum(comm_panel$`Treated community` == 1),
  sum(comm_panel$`Treated community` == 0)))

# ---------------------------------------------------------------------
# 4. Appendix Table — comprehensive summary statistics for every
#    conceptual variable used in the analysis (skipping ID columns,
#    spec variants beyond the legacy/SAR primary, and intermediate-only
#    items). Grouped into panels for readability.
# ---------------------------------------------------------------------
appendix_groups <- list(
  "Demographics and geography" = c(
    Female                          = "Female",
    `Age in 2014`                   = "Age in 2014",
    `Birth year`                    = "Birth year",
    `Birth month`                   = "Birth month",
    `Province (Java or Bali)`       = "Province (Java or Bali)"),
  "Mother characteristics" = c(
    `Mother's age at birth`         = "Mother's age at birth",
    `Mother's years of schooling`   = "Mother's years of schooling",
    `Mother's height (cm)`          = "Mother's height (cm)",
    `Mother smokes`                 = "mother_smoke",
    `Mother is non-migrant`         = "mother_non_migrant",
    `Mother education missing`      = "mother_edu_miss"),
  "Program exposure (main: SAR-preferred)" = c(
    `Village midwife start year`    = "start_sar_legacy",
    `Age at midwife arrival`        = "age_at_rollout_sar_legacy",
    `In utero at arrival`           = "inutero_sar_legacy",
    `Exposed in utero or age 0--3`  = "exposure_early_sar_legacy",
    `Exposed within ages 0--3 only` = "within_3_sar_legacy",
    `Exposed within ages 4--6`      = "within_46_sar_legacy"),
  "Other facility presence (community of birth)" = c(
    `Has clinic (puskesmas)`        = "has_clinic",
    `Has doctor`                    = "has_doctor",
    `Has private midwife`           = "has_private_midwife",
    `Has traditional midwife`       = "has_traditional_midwife"),
  "Health outcomes (wave 5 adult)" = c(
    `Standing height (cm)`          = "height_cm",
    `BMI`                           = "bmi",
    `Not underweight (BMI >= 18.5)` = "no_underweight",
    `Log peak expiratory flow`      = "lung_log",
    `Diastolic BP (mmHg)`           = "bp_diast_mean",
    `Systolic BP (mmHg)`            = "bp_syst_mean",
    `Not hypertensive`              = "no_hypertension",
    `Good early-life health`        = "good_early_health",
    `General health self-rating`    = "ghs",
    `Health index (Anderson)`       = "health_index"),
  "Cognition outcomes (wave 5 adult)" = c(
    `Adult IRT score (w\\_abil)`    = "w_abil",
    `Serial-7 subtraction (0--5)`   = "serial7_correct",
    `Immediate word recall (0--10)` = "immed_count",
    `Delayed word recall (0--10)`   = "delay_count",
    `Memory test (days survey)`     = "memory_days",
    `Math share correct (child)`    = "math_prop_child",
    `Cognition share correct (child)` = "cog_prop_child",
    `Cognition index (Anderson)`    = "cognition_index"),
  "Depression outcomes (wave 5 CESD-10)" = c(
    `Depression raw sum`            = "dep_index",
    `CESD-10 items reported (0--10)`= "n_dep_items",
    `Not depressed`                 = "no_depression",
    `Depression index (sign-flipped)` = "depression_index",
    `CESD-10: bothered`             = "kp02_A",
    `CESD-10: poor appetite`        = "kp02_B",
    `CESD-10: blues`                = "kp02_C",
    `CESD-10: as good as others`    = "kp02_D",
    `CESD-10: trouble concentrating`= "kp02_E",
    `CESD-10: depressed`            = "kp02_F",
    `CESD-10: everything an effort` = "kp02_G",
    `CESD-10: hopeful`              = "kp02_H",
    `CESD-10: fearful`              = "kp02_I",
    `CESD-10: sleep restless`       = "kp02_J"),
  "Socioemotional outcomes (Big-Five)" = c(
    Agreeableness                   = "agreeableness",
    Conscientiousness               = "conscientiousness",
    Extraversion                    = "extraversion",
    `Emotional stability`           = "emotional_stability",
    Openness                        = "openness",
    `Big-Five composite index`      = "bigfive_index"),
  "Mediators (mother-reported pregnancy history)" = c(
    `Any prenatal check-up`         = "pnc_any",
    `Ever breastfed`                = "ever_breastfed",
    `Not sick in past month`        = "notsick_a_month"),
  "Sample weights and flags" = c(
    `Primary sample`                = "primary_sample",
    `Mother (sibling) sample`       = "mother_sample",
    `Preceding-wave sample`         = "preceding_sample",
    `Deceased before wave 5`        = "dead",
    `Migrant (any wave)`            = "migrant",
    `Non-migrant (all waves)`       = "non_migrant",
    `Inverse-probability weight`    = "ipw")
)

# Use the primary-sample frame for all appendix entries that exist
# at the individual level. (Adding a separate community panel here
# would clutter; the community-level Treated indicator already lives
# in Table 1 Panel B.)
build_group_rows <- function(group_name, var_map) {
  c(sprintf("\\multicolumn{7}{l}{\\emph{%s}} \\\\", group_name),
    vapply(seq_along(var_map),
           function(i) {
             colnm <- var_map[i]
             label <- names(var_map)[i]
             if (!colnm %in% names(prim)) {
               return(sprintf("%s & --- & --- & --- & --- & --- & --- \\\\",
                              label))
             }
             format_summary_row(prim[[colnm]], label)
           },
           character(1)))
}

appendix_rows <- unlist(lapply(seq_along(appendix_groups), function(i) {
  group_name <- names(appendix_groups)[i]
  rows <- build_group_rows(group_name, appendix_groups[[i]])
  if (i < length(appendix_groups)) c(rows, "\\midrule") else rows
}))

appendix_lines <- c(
  "\\begin{longtable}{lrrrrrr}",
  "\\caption{Comprehensive summary statistics for every analysis-frame variable (primary sample).}\\label{tab:appendix_summary}\\\\",
  "\\toprule",
  "Variable & N & Mean & SD & Min & Median & Max \\\\",
  "\\midrule",
  "\\endfirsthead",
  "\\multicolumn{7}{l}{\\emph{Table~\\ref{tab:appendix_summary} continued.}}\\\\",
  "\\toprule",
  "Variable & N & Mean & SD & Min & Median & Max \\\\",
  "\\midrule",
  "\\endhead",
  "\\midrule",
  "\\multicolumn{7}{r}{\\emph{Continued on next page.}}\\\\",
  "\\endfoot",
  "\\bottomrule",
  "\\endlastfoot",
  appendix_rows,
  "\\end{longtable}"
)

writeLines(appendix_lines,
           file.path(tables_dir, "appendix_summary_stats.tex"))

log_stage("stage07", sprintf(
  "Appendix summary table written: %d variable groups, %d individual variables.",
  length(appendix_groups), sum(lengths(appendix_groups))))

# ---------------------------------------------------------------------
# 4. Rollout histogram (distribution of start_year_sar across commids).
# ---------------------------------------------------------------------
palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

p_roll <- rollout |>
  filter(!is.na(start_year_sar)) |>
  ggplot(aes(x = start_year_sar)) +
  geom_histogram(binwidth = 1, fill = palette_oi["blue"],
                 colour = "white", alpha = 0.9) +
  geom_vline(xintercept = 1989, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  geom_vline(xintercept = 1997, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  annotate("text", x = 1989, y = Inf, label = "Program start (1989)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  annotate("text", x = 1997, y = Inf, label = "AFC onset (1997)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  scale_x_continuous(breaks = seq(1989, 2015, by = 3)) +
  labs(x = "First-observed SAR rollout year",
       y = "Communities",
       title = NULL) +
  theme_bw(base_size = 11) +
  theme(panel.grid.minor = element_blank())

ggsave(file.path(figures_dir, "rollout_histogram.pdf"),
       plot = p_roll, width = 6.5, height = 4.0, units = "in",
       device = cairo_pdf, bg = "white")

log_stage("stage07", "rollout histogram written.")
log_stage("stage07", "done")
