# =====================================================================
# 07_balance_descriptives.R — Balance test + Table 1 + rollout diagnostics
#
# Inputs :  data/intermediate/stage06/analysis_sample.rds
#           data/intermediate/stage03/midwife_rollout.rds
#           data/intermediate/stage03/rollout_comparison.rds
#           data/intermediate/stage03/other_facilities.rds
#
# Outputs:  paper/tables/balance.tex
#           paper/tables/rollout_sar_vs_pkk.tex
#           paper/tables/table1_descriptives.tex
#           paper/figures/rollout_histogram.pdf
#
# Purpose: document the endogeneity of VM placement (the balance table
# is expected to reject random placement — this motivates the identi-
# fication stack), summarise the SAR vs PKK disagreement that the
# regression plan inherits, and produce the paper's Table 1.
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
  library(modelsummary)
  library(fixest)
})

# Use plain booktabs output rather than tabularray (one fewer
# dependency to drop into the paper preamble).
options(modelsummary_factory_latex = "kableExtra",
        modelsummary_format_numeric_latex = "plain")

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage07", "begin")

frame    <- read_intermediate("stage06", "analysis_sample")
rollout  <- read_intermediate("stage03", "midwife_rollout")
compare  <- read_intermediate("stage03", "rollout_comparison")
other_f  <- read_intermediate("stage03", "other_facilities")

tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------
# 1. Balance table on pre-treatment individual covariates.
#    Compare children in early-treated vs late-treated communities on
#    mother and child characteristics fixed at (or before) birth. If
#    placement were random, the two groups should be similar on these
#    pre-determined covariates.
#    Early / late split at the median SAR rollout year among treated
#    communities; non-migrants by the preceding-wave variant.
# ---------------------------------------------------------------------
bal_sample <- frame |>
  filter(primary_sample == 1,
         !is.na(start_sar_legacy)) |>
  mutate(
    early_village = as.integer(
      start_sar_legacy <=
        stats::median(start_sar_legacy, na.rm = TRUE))
  )

balance_rows <- tibble::tribble(
  ~varname,           ~label,
  "mother_edu_years", "Mother's education (years)",
  "mother_age_birth", "Mother's age at birth (years)",
  "mother_height",    "Mother's height (cm)",
  "female",           "Female"
) |>
  mutate(female = NA_integer_)  # placeholder; `female` built inline

# Build the `female` column once and bind to bal_sample.
bal_sample$female <- as.integer(bal_sample$sex == 3)

balance_tbl <- lapply(
  c("mother_edu_years", "mother_age_birth", "mother_height", "female"),
  function(v) {
    a <- bal_sample[[v]][bal_sample$early_village == 1]
    b <- bal_sample[[v]][bal_sample$early_village == 0]
    tt <- tryCatch(stats::t.test(a, b), error = function(e) NULL)
    tibble::tibble(
      Variable   = v,
      Early_mean = mean(a, na.rm = TRUE),
      Late_mean  = mean(b, na.rm = TRUE),
      Difference = mean(a, na.rm = TRUE) - mean(b, na.rm = TRUE),
      p_value    = if (!is.null(tt)) tt$p.value else NA_real_,
      N_early    = sum(!is.na(a)),
      N_late     = sum(!is.na(b))
    )
  }) |> bind_rows()

pretty_var <- c(
  mother_edu_years = "Mother's education (years)",
  mother_age_birth = "Mother's age at birth (years)",
  mother_height    = "Mother's height (cm)",
  female           = "Female"
)
balance_tbl$label <- pretty_var[balance_tbl$Variable]

# Stars on difference p-values.
stars <- ifelse(is.na(balance_tbl$p_value), "",
         ifelse(balance_tbl$p_value < 0.01, "$^{***}$",
         ifelse(balance_tbl$p_value < 0.05, "$^{**}$",
         ifelse(balance_tbl$p_value < 0.10, "$^{*}$", ""))))

writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lrrrr}",
  "\\toprule",
  "Variable & Early-rollout mean & Late-rollout mean & Difference & $p$-value \\\\",
  "\\midrule",
  vapply(seq_len(nrow(balance_tbl)), function(i) sprintf(
    "%s & %.3f & %.3f & %.3f%s & %.3f \\\\",
    balance_tbl$label[i],
    balance_tbl$Early_mean[i],
    balance_tbl$Late_mean[i],
    balance_tbl$Difference[i],
    stars[i],
    balance_tbl$p_value[i]
  ), character(1)),
  "\\midrule",
  sprintf("$N$ (children) & \\multicolumn{2}{c}{%s / %s} & & \\\\",
          format(balance_tbl$N_early[1], big.mark = ","),
          format(balance_tbl$N_late[1], big.mark = ",")),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "balance.tex"))

log_stage("stage07", sprintf(
  "balance table: %d covariates (early vs late-treated villages).",
  nrow(balance_tbl)))

# ---------------------------------------------------------------------
# 2. SAR vs PKK rollout diagnostic table.
# ---------------------------------------------------------------------
both <- compare |> filter(has_both == 1)
rc <- tibble::tibble(
  Metric = c("Communities total",
             "With SAR start-year",
             "With PKK start-year",
             "With both",
             "Pearson rho(SAR, PKK)",
             "Share disagreeing (both present)",
             "Mean |SAR - PKK| (years)"),
  Value  = c(nrow(compare),
             sum(compare$has_sar),
             sum(compare$has_pkk),
             nrow(both),
             if (nrow(both) > 3)
               round(cor(both$start_year_sar,
                         both$start_year_pkk, use = "complete.obs"), 3)
             else NA_real_,
             round(mean(both$start_year_sar != both$start_year_pkk), 3),
             round(mean(abs(both$delta), na.rm = TRUE), 2))
)

writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lr}",
  "\\toprule",
  "Metric & Value \\\\",
  "\\midrule",
  apply(rc, 1, function(r) sprintf("%s & %s \\\\",
                                   r["Metric"], r["Value"])),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "rollout_sar_vs_pkk.tex"))

log_stage("stage07", sprintf(
  "rollout diagnostic: %d commids with both; rho=%.3f; disagree=%.3f",
  nrow(both), rc$Value[5], rc$Value[6]))

# ---------------------------------------------------------------------
# 3. Table 1 — descriptive statistics on the primary sample.
# ---------------------------------------------------------------------
t1 <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    Exposed = factor(ifelse(exposure_early_sar_legacy == 1,
                            "Exposed", "Control"),
                     levels = c("Exposed", "Control")),
    # IFLS roster ar07: 1 = male, 3 = female.
    Female  = as.integer(sex == 3),
    age2014 = 2014 - birth_year
  ) |>
  select(
    Exposed,
    Female,
    `Age in 2014 (years)`                = age2014,
    `Birth year`                         = birth_year,
    `Mother's education (years)`         = mother_edu_years,
    `Mother's age at birth (years)`      = mother_age_birth,
    `Child height (cm)`                  = height_cm,
    `Word-recall score`                  = w_abil,
    `CESD-10 depression score (raw)`     = dep_index,
    `Health index (std.)`                = health_index,
    `Cognition index (std.)`             = cognition_index,
    `Depression index (std., higher = better)` = depression_index,
    `Socioemotional index (std.)`        = bigfive_index
  )

datasummary(
  All(t1) ~ Exposed * (Mean + SD),
  data = t1,
  output = file.path(tables_dir, "table1_descriptives.tex"),
  fmt = 3,
  title = "Descriptive statistics (primary sample).",
  notes = "VM = village midwife. See Section text for sample definition."
)

log_stage("stage07", sprintf("Table 1 written for N=%d.", nrow(t1)))

# ---------------------------------------------------------------------
# 4. Rollout histogram (distribution of start_year_sar across commids).
# ---------------------------------------------------------------------
palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

p_roll <- rollout |>
  filter(!is.na(start_year_sar)) |>
  ggplot(aes(x = start_year_sar)) +
  geom_histogram(binwidth = 1, fill = palette_oi["blue"],
                 colour = "white", alpha = 0.9) +
  geom_vline(xintercept = 1989, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  geom_vline(xintercept = 1997, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  annotate("text", x = 1989, y = Inf, label = "Program start (1989)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  annotate("text", x = 1997, y = Inf, label = "AFC onset (1997)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  scale_x_continuous(breaks = seq(1989, 2015, by = 3)) +
  labs(x = "First-observed SAR rollout year",
       y = "Communities",
       title = NULL) +
  theme_bw(base_size = 11) +
  theme(panel.grid.minor = element_blank())

ggsave(file.path(figures_dir, "rollout_histogram.pdf"),
       plot = p_roll, width = 6.5, height = 4.0, units = "in",
       device = cairo_pdf, bg = "white")

log_stage("stage07", "rollout histogram written.")
log_stage("stage07", "done")
