# =====================================================================
# 07_balance_descriptives.R — Balance test + Table 1 + rollout diagnostics
#
# Inputs :  data/intermediate/stage06/analysis_sample.rds
#           data/intermediate/stage03/midwife_rollout.rds
#           data/intermediate/stage03/rollout_comparison.rds
#           data/intermediate/stage03/other_facilities.rds
#
# Outputs:  paper/tables/balance.tex
#           paper/tables/rollout_sar_vs_pkk.tex
#           paper/tables/table1_descriptives.tex
#           paper/figures/rollout_histogram.pdf
#
# Purpose: document the endogeneity of VM placement (the balance table
# is expected to reject random placement — this motivates the identi-
# fication stack), summarise the SAR vs PKK disagreement that the
# regression plan inherits, and produce the paper's Table 1.
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(ggplot2)
  library(modelsummary)
  library(fixest)
})

# Use plain booktabs output rather than tabularray (one fewer
# dependency to drop into the paper preamble).
options(modelsummary_factory_latex = "kableExtra",
        modelsummary_format_numeric_latex = "plain")

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))

log_stage("stage07", "begin")

frame    <- read_intermediate("stage06", "analysis_sample")
rollout  <- read_intermediate("stage03", "midwife_rollout")
compare  <- read_intermediate("stage03", "rollout_comparison")
other_f  <- read_intermediate("stage03", "other_facilities")

tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------
# 1. Balance table at commid93 level.
#    For each village covariate, regress on start_year_sar (continuous)
#    and on treated_ever. If placement were random, coefficients should
#    be near zero. We expect them NOT to be — the point is to document
#    the problem that identification (stage 08–11) has to solve.
# ---------------------------------------------------------------------
vill <- rollout |>
  select(commid93, start_year_sar, present_any_sar) |>
  left_join(other_f, by = "commid93") |>
  mutate(
    treated_ever = as.integer(!is.na(start_year_sar)),
    # Early vs late cut at median start_year_sar among treated villages.
    early_treated = as.integer(
      !is.na(start_year_sar) &
      start_year_sar <= stats::median(start_year_sar, na.rm = TRUE))
  )

balance_vars <- c("has_doctor", "has_clinic",
                  "has_private_midwife", "has_traditional_midwife")

# For each var: mean among early-treated, mean among late-treated, diff,
# p-value from a t-test.
balance_rows <- lapply(balance_vars, function(v) {
  a <- vill[[v]][vill$treated_ever == 1 & vill$early_treated == 1]
  b <- vill[[v]][vill$treated_ever == 1 & vill$early_treated == 0]
  tt <- tryCatch(stats::t.test(a, b), error = function(e) NULL)
  tibble(
    Variable    = v,
    Early_mean  = mean(a, na.rm = TRUE),
    Late_mean   = mean(b, na.rm = TRUE),
    Difference  = mean(a, na.rm = TRUE) - mean(b, na.rm = TRUE),
    p_value     = if (!is.null(tt)) tt$p.value else NA_real_
  )
})
balance_tbl <- bind_rows(balance_rows)

# Write as a simple LaTeX table via modelsummary::datasummary_* pathway
# isn't ideal here; hand-roll a small longtable-free block.
writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lrrrr}",
  "\\toprule",
  "Variable & Early-treated mean & Late-treated mean & Diff. & $p$-value \\\\",
  "\\midrule",
  apply(balance_tbl, 1, function(r) sprintf(
    "%s & %.3f & %.3f & %.3f & %.3f \\\\",
    gsub("_", "\\\\_", r["Variable"]),
    as.numeric(r["Early_mean"]),
    as.numeric(r["Late_mean"]),
    as.numeric(r["Difference"]),
    as.numeric(r["p_value"])
  )),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "balance.tex"))

log_stage("stage07", sprintf(
  "balance table: %d covariates (early vs late-treated villages).",
  nrow(balance_tbl)))

# ---------------------------------------------------------------------
# 2. SAR vs PKK rollout diagnostic table.
# ---------------------------------------------------------------------
both <- compare |> filter(has_both == 1)
rc <- tibble::tibble(
  Metric = c("Communities total",
             "With SAR start-year",
             "With PKK start-year",
             "With both",
             "Pearson rho(SAR, PKK)",
             "Share disagreeing (both present)",
             "Mean |SAR - PKK| (years)"),
  Value  = c(nrow(compare),
             sum(compare$has_sar),
             sum(compare$has_pkk),
             nrow(both),
             if (nrow(both) > 3)
               round(cor(both$start_year_sar,
                         both$start_year_pkk, use = "complete.obs"), 3)
             else NA_real_,
             round(mean(both$start_year_sar != both$start_year_pkk), 3),
             round(mean(abs(both$delta), na.rm = TRUE), 2))
)

writeLines(c(
  "% Auto-generated by code/R/07_balance_descriptives.R",
  "\\begin{tabular}{lr}",
  "\\toprule",
  "Metric & Value \\\\",
  "\\midrule",
  apply(rc, 1, function(r) sprintf("%s & %s \\\\",
                                   r["Metric"], r["Value"])),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "rollout_sar_vs_pkk.tex"))

log_stage("stage07", sprintf(
  "rollout diagnostic: %d commids with both; rho=%.3f; disagree=%.3f",
  nrow(both), rc$Value[5], rc$Value[6]))

# ---------------------------------------------------------------------
# 3. Table 1 — descriptive statistics on the primary sample.
# ---------------------------------------------------------------------
t1 <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    Exposed   = factor(ifelse(exposure_early_sar_preceding == 1,
                              "Exposed", "Control"),
                       levels = c("Exposed", "Control")),
    Female    = as.integer(sex == 2),
    Age2014   = 2014 - birth_year
  ) |>
  select(Exposed, Female, Age2014, birth_year,
         mother_edu_years, mother_age_birth,
         height_cm, w_abil, dep_index, health_index,
         cognition_index, depression_index, bigfive_index)

datasummary(
  All(t1) ~ Exposed * (Mean + SD),
  data = t1,
  output = file.path(tables_dir, "table1_descriptives.tex"),
  fmt = 3,
  title = "Descriptive statistics (primary sample).",
  notes = "VM = village midwife. See Section text for sample definition."
)

log_stage("stage07", sprintf("Table 1 written for N=%d.", nrow(t1)))

# ---------------------------------------------------------------------
# 4. Rollout histogram (distribution of start_year_sar across commids).
# ---------------------------------------------------------------------
palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

p_roll <- rollout |>
  filter(!is.na(start_year_sar)) |>
  ggplot(aes(x = start_year_sar)) +
  geom_histogram(binwidth = 1, fill = palette_oi["blue"],
                 colour = "white", alpha = 0.9) +
  geom_vline(xintercept = 1989, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  geom_vline(xintercept = 1997, linetype = "dashed",
             colour = palette_oi["vermilion"]) +
  annotate("text", x = 1989, y = Inf, label = "Program start (1989)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  annotate("text", x = 1997, y = Inf, label = "AFC onset (1997)",
           hjust = -0.05, vjust = 1.5, size = 3) +
  scale_x_continuous(breaks = seq(1989, 2015, by = 3)) +
  labs(x = "First-observed SAR rollout year",
       y = "Communities",
       title = NULL) +
  theme_minimal(base_size = 11) +
  theme(panel.grid.minor = element_blank())

ggsave(file.path(figures_dir, "rollout_histogram.pdf"),
       plot = p_roll, width = 6.5, height = 4.0, units = "in",
       device = cairo_pdf, bg = "white")

log_stage("stage07", "rollout histogram written.")
log_stage("stage07", "done")
