# =====================================================================
# 09_event_study.R — Event study via Sun-Abraham + CS dynamic aggregation.
#
# For each primary outcome: event-time coefficients and 95% CIs,
# centred on event-time -1 (reference). Produces one figure per outcome
# and a joint F-test on pre-period coefficients (reviewer's first ask).
#
# Inputs :  data/intermediate/stage06/analysis_sample.rds
#           data/output/regressions/stage08_models.rds  (CS att_gt)
#
# Outputs:  paper/figures/event_study_<outcome>.pdf     (× 4)
#           paper/tables/event_study_pretrend_tests.tex
#           paper/tables/event_study_<outcome>.tex       (× 4)
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tibble)
  library(fixest)
  library(did)
  library(ggplot2)
})

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage09", "begin")

frame <- read_intermediate("stage06", "analysis_sample")
stage08 <- readRDS(here::here("data", "output", "regressions",
                              "stage08_models.rds"))

tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

df <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    G = if_else(!is.na(start_sar_legacy),
                as.integer(start_sar_legacy) - 1L, 0L),
    # Sun-Abraham `sunab()` wants first_treat = NA for never-treated.
    first_treat = if_else(G > 0, G, NA_integer_)
  )

outcomes <- c("health_index", "cognition_index",
              "depression_index", "bigfive_index")

# ---------------------------------------------------------------------
# 1. Sun-Abraham per outcome.
#    Reference event-time = -1 (default in sunab).  Bin endpoints at
#    ±8 to avoid thin cells at extreme leads/lags.
# ---------------------------------------------------------------------
# Display window: trim leads before -4 and lags after +8. Pre-period
# leads -10..-5 are hidden because the extreme leads are noisy and
# (per sensitivity-analysis convention) the -4..-2 window is what the
# parallel-trends assumption is actually identified off.
ET_MIN <- -4L
ET_MAX <-  8L

pretrend_rows <- list()
for (y in outcomes) {
  log_stage("stage09", sprintf("Sun-Abraham event study for %s", y))
  m <- feols(
    as.formula(sprintf(
      "%s ~ sunab(first_treat, birth_year, ref.p = -1) | commid_birth_legacy + birth_year",
      y)),
    data = df, cluster = ~ commid_birth_legacy
  )
  # Per-event-time (cohort-aggregated) coefficients from iplot data.
  ip <- iplot(m, only.params = TRUE)$prms
  etcoef <- tibble(
    event_time = as.integer(as.character(ip$estimate_names)),
    estimate   = ip$estimate,
    ci_lo      = ip$ci_low,
    ci_hi      = ip$ci_high,
    is_ref     = ip$is_ref
  ) |>
    mutate(se = (ci_hi - ci_lo) / (2 * 1.96)) |>
    filter(event_time >= ET_MIN, event_time <= ET_MAX) |>
    arrange(event_time)

  # Pre-trend joint Wald test over event-times [ET_MIN, -2] using
  # fixest::wald(). The named regex matches the cohort-specific
  # sunab interactions and fixest aggregates internally.
  w_expr <- sprintf("birth_year::(%s):",
                    paste(setdiff(ET_MIN:(-2), -1),
                          collapse = "|"))
  w_test <- tryCatch(fixest::wald(m, keep = w_expr, print = FALSE),
                     error = function(e) NULL)
  if (!is.null(w_test) && !is.na(w_test$p)) {
    W      <- w_test$stat
    df_pre <- w_test$df1
    p_val  <- w_test$p
  } else {
    W <- NA_real_; df_pre <- 0L; p_val <- NA_real_
  }
  pretrend_rows[[y]] <- tibble(outcome = y, chi2 = W,
                               df = df_pre, p_value = p_val)
}

# The per-outcome Sun-Abraham event-time coefficient tables and the
# per-outcome Sun-Abraham event-study PDFs were dropped 2026-04-21.
# At extreme leads (event-time <= -3) the treated cohort has very few
# observed villages, so the Sun-Abraham aggregation produces SEs on
# the order of 70+ SD; the resulting .tex tables were unpresentable
# and the PDFs had error bars that ran off the y-axis. The CS event-
# study figures in paper/figures/event_study_CS_*.pdf are the paper's
# visual evidence on pre-trends and dynamics; the Sun-Abraham fits
# are retained here only to compute the joint pre-trend Wald test
# reported in paper/tables/event_study_pretrend_tests.tex below.

pretrend_tbl <- bind_rows(pretrend_rows)

writeLines(c(
  "% Auto-generated by code/R/09_event_study.R",
  "\\begin{tabular}{lccc}",
  "\\toprule",
  "Outcome & Wald $\\chi^2$ & df & $p$-value \\\\",
  "\\midrule",
  apply(pretrend_tbl, 1, function(r) sprintf(
    "%s & %.2f & %d & %.3f \\\\",
    pretty_label(r["outcome"]),
    as.numeric(r["chi2"]),
    as.integer(r["df"]),
    as.numeric(r["p_value"])
  )),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "event_study_pretrend_tests.tex"))

log_stage("stage09", sprintf("pre-trend p-values: %s",
                             paste(sprintf("%s=%.3f",
                                           pretrend_tbl$outcome,
                                           pretrend_tbl$p_value),
                                   collapse = "; ")))

# ---------------------------------------------------------------------
# 2. CS dynamic aggregation figures (complement to Sun-Abraham).
#    Loads att_gt objects from stage 08 and plots event-study.
# ---------------------------------------------------------------------
for (y in outcomes) {
  att_obj <- stage08$cs[[y]]$att
  if (is.null(att_obj)) next
  dyn <- tryCatch(aggte(att_obj, type = "dynamic",
                        min_e = ET_MIN, max_e = ET_MAX, na.rm = TRUE),
                  error = function(e) NULL)
  if (is.null(dyn)) next
  # Narrow the displayed CS event-time window to [-3, +4]. Beyond
  # event-time +4 the cohort-village cells become very sparse (the
  # program rolled out through the late 1990s and wave 5 is 2014, so
  # only narrow combinations of start_year and birth_year reach
  # event-time 5 or higher); the CS group-time ATTs at those event
  # times are noisy outliers and would distort the plot scales.
  PLOT_MIN <- -3L
  PLOT_MAX <-  4L
  d <- tibble(event_time = dyn$egt,
              estimate   = dyn$att.egt,
              se         = dyn$se.egt) |>
    mutate(ci_lo = estimate - 1.96 * se,
           ci_hi = estimate + 1.96 * se) |>
    filter(event_time >= PLOT_MIN, event_time <= PLOT_MAX)

  p <- ggplot(d, aes(x = event_time, y = estimate)) +
    geom_hline(yintercept = 0, linetype = "dashed",
               colour = palette_oi["black"], alpha = 0.5) +
    geom_vline(xintercept = -0.5, linetype = "dotted",
               colour = palette_oi["vermilion"]) +
    geom_errorbar(aes(ymin = ci_lo, ymax = ci_hi), width = 0.2,
                  colour = palette_oi["blue"]) +
    geom_point(size = 2, colour = palette_oi["blue"]) +
    scale_x_continuous(breaks = seq(PLOT_MIN, PLOT_MAX, by = 1),
                       limits = c(PLOT_MIN - 0.5, PLOT_MAX + 0.5)) +
    labs(x = "Birth cohort relative to VM rollout (years)",
         y = sprintf("CS dynamic ATT: %s", pretty_label(y))) +
    theme_bw(base_size = 11) +
    theme(panel.grid.minor = element_blank())

  ggsave(file.path(figures_dir, sprintf("event_study_CS_%s.pdf", y)),
         plot = p, width = 6.5, height = 4.0, units = "in",
         device = cairo_pdf, bg = "white")
}

log_stage("stage09", "done")
