# =====================================================================
# 12_heterogeneity_finalize.R — Heterogeneity + numbers.tex + forest plot.
#
# Heterogeneity dimensions:
#   * By mother education (low/high split at median)
#   * By exposure window: inutero / age 0-3 / age 4-6 / age 7+
#   * By rural/urban (commid urban classification via province codes —
#     IFLS does not have a clean rural/urban flag; we approximate by
#     province codes where Jakarta/DKI (31) and other heavily urban
#     kabupatens count as "urban". This is coarse and flagged as such.)
#
# Outputs:
#   paper/tables/heterogeneity_mother_edu.tex
#   paper/tables/heterogeneity_age_window.tex
#   paper/figures/heterogeneity_forest.pdf
#   paper/numbers.tex  — \newcommand for in-text numbers
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(fixest)
  library(ggplot2)
})

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage12", "begin")

frame <- read_intermediate("stage06", "analysis_sample")
tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

df <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    sex_f = factor(sex, levels = c(1, 3),
                   labels = c("male", "female")),
    high_medu = as.integer(mother_edu_years >
                             stats::median(mother_edu_years,
                                           na.rm = TRUE)),
    age_win = case_when(
      inutero_sar_legacy   == 1 ~ "in utero",
      within_3_sar_legacy  == 1 ~ "age 0-3",
      within_46_sar_legacy == 1 ~ "age 4-6",
      !is.na(age_at_rollout_sar_legacy) &
        age_at_rollout_sar_legacy >= 7 ~ "age 7+",
      TRUE ~ "never / pre-VM"
    ) |> factor(levels = c("never / pre-VM", "in utero",
                           "age 0-3", "age 4-6", "age 7+"))
  )

outcomes <- c("health_index", "cognition_index",
              "depression_index", "bigfive_index")

coef_se <- function(m, var) {
  if (is.null(m) || !var %in% names(coef(m))) return(c(NA, NA))
  c(unname(coef(m)[var]),
    unname(sqrt(vcov(m)[var, var])))
}
fmt <- function(est, se) {
  if (is.na(est)) return("---")
  sprintf("%.3f\n(%.3f)", est, se)
}

# ---------------------------------------------------------------------
# 1. Heterogeneity by mother education.
# ---------------------------------------------------------------------
rows_edu <- lapply(outcomes, function(y) {
  ml <- feols(as.formula(sprintf(paste0(
    "%s ~ exposure_early_sar_legacy | ",
    "commid_birth_legacy + birth_year"), y)),
    data = df |> filter(high_medu == 0),
    cluster = ~ commid_birth_legacy)
  mh <- feols(as.formula(sprintf(paste0(
    "%s ~ exposure_early_sar_legacy | ",
    "commid_birth_legacy + birth_year"), y)),
    data = df |> filter(high_medu == 1),
    cluster = ~ commid_birth_legacy)
  pl <- coef_se(ml, "exposure_early_sar_legacy")
  ph <- coef_se(mh, "exposure_early_sar_legacy")
  tibble(outcome = y,
         `Low-edu`  = fmt(pl[1], pl[2]),
         `High-edu` = fmt(ph[1], ph[2]))
})
edu_tbl <- bind_rows(rows_edu)

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "\\begin{tabular}{lcc}",
  "\\toprule",
  "Outcome & Low-edu mother & High-edu mother \\\\",
  "\\midrule",
  apply(edu_tbl, 1, function(r) {
    cells <- vapply(r[-1], function(cell)
      paste0("\\makecell{", gsub("\n", "\\\\\\\\", cell), "}"),
      character(1))
    sprintf("%s & %s \\\\", pretty_label(r["outcome"]),
            paste(cells, collapse = " & "))
  }),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "heterogeneity_mother_edu.tex"))

# ---------------------------------------------------------------------
# 2. Heterogeneity by age-window (separate dummies for inutero,
#    0-3, 4-6, 7+, with pre-VM / never-treated as reference).
# ---------------------------------------------------------------------
rows_age <- lapply(outcomes, function(y) {
  m <- feols(as.formula(sprintf(paste0(
    "%s ~ i(age_win, ref = 'never / pre-VM') | ",
    "commid_birth_legacy + birth_year"), y)),
    data = df, cluster = ~ commid_birth_legacy)
  co <- coef(m); vc <- vcov(m)
  get <- function(lbl) {
    nm <- grep(paste0("age_win::", lbl, "$"), names(co), value = TRUE)
    if (length(nm) == 0) return(c(NA, NA))
    c(co[nm], sqrt(vc[nm, nm]))
  }
  iu <- get("in utero"); a03 <- get("age 0-3"); a46 <- get("age 4-6")
  a7  <- get("age 7\\+")
  tibble(outcome  = y,
         `In utero` = fmt(iu[1],  iu[2]),
         `0-3`      = fmt(a03[1], a03[2]),
         `4-6`      = fmt(a46[1], a46[2]),
         `7+`       = fmt(a7[1],  a7[2]))
})
age_tbl <- bind_rows(rows_age)

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "\\begin{tabular}{lcccc}",
  "\\toprule",
  "Outcome & In utero & Age 0--3 & Age 4--6 & Age 7+ \\\\",
  "\\midrule",
  apply(age_tbl, 1, function(r) {
    cells <- vapply(r[-1], function(cell)
      paste0("\\makecell{", gsub("\n", "\\\\\\\\", cell), "}"),
      character(1))
    sprintf("%s & %s \\\\", pretty_label(r["outcome"]),
            paste(cells, collapse = " & "))
  }),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "heterogeneity_age_window.tex"))

# ---------------------------------------------------------------------
# 3. Heterogeneity forest plot.
#    Run by-sex + by-mother-edu for each outcome; collect coefs; plot.
# ---------------------------------------------------------------------
forest_rows <- list()
for (y in outcomes) {
  subsets <- list(
    "Full sample" = df,
    "Male"        = df |> filter(sex == 1),
    "Female"      = df |> filter(sex == 3),
    "Low-edu"     = df |> filter(high_medu == 0),
    "High-edu"    = df |> filter(high_medu == 1)
  )
  for (nm in names(subsets)) {
    d <- subsets[[nm]]
    m <- feols(as.formula(sprintf(paste0(
      "%s ~ exposure_early_sar_legacy | ",
      "commid_birth_legacy + birth_year"), y)),
      data = d, cluster = ~ commid_birth_legacy)
    p <- coef_se(m, "exposure_early_sar_legacy")
    forest_rows[[paste(y, nm)]] <- tibble(
      outcome = y, subgroup = nm,
      estimate = p[1], se = p[2],
      ci_lo = p[1] - 1.96 * p[2], ci_hi = p[1] + 1.96 * p[2]
    )
  }
}
forest <- bind_rows(forest_rows) |>
  mutate(
    outcome = factor(outcome, levels = outcomes,
                     labels = c("Health", "Cognition",
                                "Depression (- )", "Socioemotional")),
    subgroup = factor(subgroup, levels = rev(c("Full sample",
                                               "Male", "Female",
                                               "Low-edu", "High-edu")))
  )

palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

p_forest <- ggplot(forest,
                   aes(x = estimate, y = subgroup)) +
  geom_vline(xintercept = 0, linetype = "dashed",
             colour = "grey40", alpha = 0.7) +
  geom_errorbar(aes(xmin = ci_lo, xmax = ci_hi),
                orientation = "y", width = 0.15,
                colour = "black", linewidth = 0.4) +
  geom_point(size = 2.2, colour = "black") +
  facet_wrap(~ outcome, ncol = 2, scales = "free_x") +
  labs(x = "Effect of VM exposure (SD)", y = NULL) +
  theme_classic(base_size = 11) +
  theme(
    panel.background = element_rect(fill = "white", colour = NA),
    plot.background  = element_rect(fill = "white", colour = NA),
    strip.background = element_rect(fill = "white", colour = "black",
                                    linewidth = 0.4),
    strip.text       = element_text(face = "bold"),
    panel.grid.major.x = element_line(colour = "grey92", linewidth = 0.3),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black", linewidth = 0.4)
  )

ggsave(file.path(figures_dir, "heterogeneity_forest.pdf"),
       plot = p_forest, width = 6.5, height = 4.0, units = "in",
       device = cairo_pdf, bg = "white")

# ---------------------------------------------------------------------
# 4. numbers.tex — in-text macros for the paper.
# ---------------------------------------------------------------------
main_m <- feols(health_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year,
                data = df, cluster = ~ commid_birth_legacy)
dep_m  <- feols(depression_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year,
                data = df, cluster = ~ commid_birth_legacy)
# Female-only depression (abstract claim: effect particularly in girls).
dep_f  <- feols(depression_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year,
                data = df |> filter(sex == 3),
                cluster = ~ commid_birth_legacy)

sib_m <- feols(depression_index ~ exposure_early_sar_legacy +
                 birth_order + mother_age_birth |
                 mother_pidlink + birth_year,
               data = df |>
                 filter(!is.na(mother_pidlink)) |>
                 group_by(mother_pidlink) |>
                 filter(n() >= 2) |>
                 mutate(birth_order = rank(birth_year,
                                           ties.method = "first")) |>
                 ungroup(),
               cluster = ~ commid_birth_legacy)

sig3 <- function(x) sprintf("%.3f", x)
writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "% In-text numerical macros for paper.tex. Regenerate when pipeline changes.",
  sprintf("\\newcommand{\\NPrimary}{%s}",
          format(nrow(df), big.mark = ",")),
  sprintf("\\newcommand{\\NVillages}{%s}",
          format(dplyr::n_distinct(df$commid_birth_legacy),
                 big.mark = ",")),
  sprintf("\\newcommand{\\NNeverTreated}{%s}",
          format(sum(is.na(df$start_sar_legacy)), big.mark = ",")),
  sprintf("\\newcommand{\\CoefHealthTWFE}{%s}",
          sig3(unname(coef(main_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEHealthTWFE}{%s}",
          sig3(sqrt(vcov(main_m)[1,1]))),
  sprintf("\\newcommand{\\CoefDepTWFE}{%s}",
          sig3(unname(coef(dep_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepTWFE}{%s}",
          sig3(sqrt(vcov(dep_m)[1,1]))),
  sprintf("\\newcommand{\\CoefDepFemale}{%s}",
          sig3(unname(coef(dep_f)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepFemale}{%s}",
          sig3(sqrt(vcov(dep_f)[1,1]))),
  sprintf("\\newcommand{\\CoefDepSibFE}{%s}",
          sig3(unname(coef(sib_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepSibFE}{%s}",
          sig3(sqrt(vcov(sib_m)["exposure_early_sar_legacy",
                                "exposure_early_sar_legacy"])))
), file.path(here::here("paper"), "numbers.tex"))

log_stage("stage12", "numbers.tex written.")
log_stage("stage12", "done")
