# =====================================================================
# 12_heterogeneity_finalize.R — Heterogeneity + numbers.tex + forest plot.
#
# Heterogeneity dimensions (three two-way splits):
#   * Mother education (<= 6 yrs / > 6 yrs of schooling, split at median)
#   * Mother age at birth (< 26 / >= 26)
#   * Region (Java provinces 31-35 plus Bali 51 vs non-Java)
#
# All three are reported in a single consolidated table with three
# two-column panels.
#
# An earlier age-window TWFE specification was dropped: the age-window
# dummies are deterministic functions of birth_year * start_year, so
# conditioning on commid x birth-year FEs left them collinear within
# cell and the clustered SEs blew up past 1,000. The critical-period
# pattern is now delivered by the Callaway-Sant'Anna event-study
# figures in stage 09 (paper/figures/event_study_CS_*.pdf).
#
# Outputs:
#   paper/tables/heterogeneity_combined.tex   — 3-panel split table
#   paper/numbers.tex  — \newcommand for in-text numbers
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tibble)
  library(fixest)
})

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage12", "begin")

frame <- read_intermediate("stage06", "analysis_sample")
tables_dir <- here::here("paper", "tables")
dir.create(tables_dir, recursive = TRUE, showWarnings = FALSE)

df <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    sex_f = factor(sex, levels = c(1, 3),
                   labels = c("male", "female")),
    high_medu = as.integer(mother_edu_years >
                             stats::median(mother_edu_years,
                                           na.rm = TRUE)),
    young_mom = as.integer(mother_age_birth < 26),
    java_bali = as.integer(province %in% c(31L, 32L, 33L, 34L, 35L, 51L))
  )

outcomes <- c("health_index", "cognition_index",
              "depression_index", "bigfive_index")

coef_se <- function(m, var) {
  if (is.null(m) || !var %in% names(coef(m))) return(c(NA, NA))
  c(unname(coef(m)[var]),
    unname(sqrt(vcov(m)[var, var])))
}
fmt <- function(est, se) {
  if (is.na(est)) return("---")
  sprintf("%.3f\n(%.3f)", est, se)
}

# ---------------------------------------------------------------------
# 1. Three-panel heterogeneity: mother education, mother age, region.
# ---------------------------------------------------------------------
fit_subset <- function(y, d) {
  m <- feols(as.formula(sprintf(paste0(
    "%s ~ exposure_early_sar_legacy | ",
    "commid_birth_legacy + birth_year + source_wave"), y)),
    data = d, cluster = ~ commid_birth_legacy)
  p <- coef_se(m, "exposure_early_sar_legacy")
  fmt(p[1], p[2])
}

het_rows <- lapply(outcomes, function(y) {
  tibble(
    outcome     = y,
    medu_low    = fit_subset(y, df |> filter(high_medu == 0)),
    medu_high   = fit_subset(y, df |> filter(high_medu == 1)),
    age_young   = fit_subset(y, df |> filter(young_mom == 1)),
    age_older   = fit_subset(y, df |> filter(young_mom == 0)),
    region_java = fit_subset(y, df |> filter(java_bali == 1)),
    region_non  = fit_subset(y, df |> filter(java_bali == 0))
  )
})
het_tbl <- bind_rows(het_rows)

# Per-panel sample sizes for the footer rows.
n_subset <- function(d) format(nrow(d), big.mark = ",")
ns <- list(
  medu_low    = n_subset(df |> filter(high_medu == 0)),
  medu_high   = n_subset(df |> filter(high_medu == 1)),
  age_young   = n_subset(df |> filter(young_mom == 1)),
  age_older   = n_subset(df |> filter(young_mom == 0)),
  region_java = n_subset(df |> filter(java_bali == 1)),
  region_non  = n_subset(df |> filter(java_bali == 0))
)

cell_lines <- apply(
  het_tbl[, c("outcome", "medu_low", "medu_high", "age_young",
              "age_older", "region_java", "region_non")],
  1, function(r) {
    cells <- vapply(r[-1], function(cell)
      paste0("\\makecell{", gsub("\n", "\\\\\\\\", cell), "}"),
      character(1))
    sprintf("%s & %s \\\\", pretty_label(r["outcome"]),
            paste(cells, collapse = " & "))
  })

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "\\begin{tabular}{lcccccc}",
  "\\toprule",
  paste("& \\multicolumn{2}{c}{Mother education}",
        "& \\multicolumn{2}{c}{Mother age at birth}",
        "& \\multicolumn{2}{c}{Region} \\\\"),
  "\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}",
  paste("Outcome & $\\leq 6$ yrs & $> 6$ yrs",
        "& $< 26$ & $\\geq 26$ & Java + Bali & Non-Java \\\\"),
  "\\midrule",
  cell_lines,
  "\\midrule",
  sprintf("Observations & %s & %s & %s & %s & %s & %s \\\\",
          ns$medu_low, ns$medu_high, ns$age_young, ns$age_older,
          ns$region_java, ns$region_non),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "heterogeneity_combined.tex"))

# Age-window TWFE block removed 2026-04-21. See header comment: the
# age dummies are collinear with the commid x birth-year FE structure,
# so clustered SEs blew up past 1,000. The critical-period pattern is
# delivered by the CS event-study figures from stage 09. A stale copy
# of paper/tables/heterogeneity_age_window.tex must also be removed
# by a one-shot command after this stage runs (see 00_run_all.R).

# ---------------------------------------------------------------------
# 2. numbers.tex — in-text macros for paper.tex and paper_predoc.tex.
#
# CS macros are pulled from stage 08's persisted att_gt objects so the
# abstract's headline values trace back to the same estimator that
# populates main_results.tex. TWFE baseline macros are recomputed here
# on the same non-migrant frame; sibling-FE macro comes from a fresh
# mother-FE fit on the >=2-sibling subsample to match the robustness
# table. Every macro below must map to a cited \macro somewhere in
# paper/sections; unused macros should be pruned to keep the file honest.
# ---------------------------------------------------------------------
stage08 <- readRDS(here::here("data", "output", "regressions",
                              "stage08_models.rds"))

# TWFE baseline (used as the "TWFE is the wrong lens" benchmark in the
# CS-vs-TWFE comparison paragraphs).
main_m <- feols(health_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year + source_wave,
                data = df, cluster = ~ commid_birth_legacy)
dep_m  <- feols(depression_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year + source_wave,
                data = df, cluster = ~ commid_birth_legacy)

# Within-mother (sibling-FE) depression, parallel to stage 10's spec A.
sib_m <- feols(depression_index ~ exposure_early_sar_legacy +
                 birth_order + mother_age_birth |
                 mother_pidlink + birth_year,
               data = df |>
                 filter(!is.na(mother_pidlink)) |>
                 group_by(mother_pidlink) |>
                 filter(n() >= 2) |>
                 mutate(birth_order = rank(birth_year,
                                           ties.method = "first")) |>
                 ungroup(),
               cluster = ~ commid_birth_legacy)

# Mediator sub-sample size (mechanisms.tex footnote).
frame_all <- read_intermediate("stage06", "analysis_sample")
n_med <- frame_all |>
  filter(preceding_sample == 1, !is.na(skilled_attendant)) |>
  nrow()

sig3   <- function(x) sprintf("%.3f", x)
cs_est <- function(y) stage08$cs[[y]]$coef
cs_se  <- function(y) stage08$cs[[y]]$se

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "% In-text numerical macros for paper.tex and paper_predoc.tex.",
  "% Regenerate via Rscript code/R/00_run_all.R when the pipeline changes.",
  "%",
  "% Sample-level macros.",
  sprintf("\\newcommand{\\NPrimary}{%s}",
          format(nrow(df), big.mark = ",")),
  sprintf("\\newcommand{\\NVillages}{%s}",
          format(dplyr::n_distinct(df$commid_birth_legacy),
                 big.mark = ",")),
  sprintf("\\newcommand{\\NPrimaryMediator}{%s}",
          format(n_med, big.mark = ",")),
  "%",
  "% Callaway-Sant'Anna dynamic ATT over event-times 0-3 (main specification).",
  sprintf("\\newcommand{\\CoefHealthCS}{%s}", sig3(cs_est("health_index"))),
  sprintf("\\newcommand{\\SEHealthCS}{%s}",   sig3(cs_se("health_index"))),
  sprintf("\\newcommand{\\CoefCogCS}{%s}",    sig3(cs_est("cognition_index"))),
  sprintf("\\newcommand{\\SECogCS}{%s}",      sig3(cs_se("cognition_index"))),
  sprintf("\\newcommand{\\CoefDepCS}{%s}",    sig3(cs_est("depression_index"))),
  sprintf("\\newcommand{\\SEDepCS}{%s}",      sig3(cs_se("depression_index"))),
  sprintf("\\newcommand{\\CoefSocCS}{%s}",    sig3(cs_est("bigfive_index"))),
  sprintf("\\newcommand{\\SESocCS}{%s}",      sig3(cs_se("bigfive_index"))),
  "%",
  "% TWFE comparator (reported as a baseline benchmark).",
  sprintf("\\newcommand{\\CoefHealthTWFE}{%s}",
          sig3(unname(coef(main_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEHealthTWFE}{%s}",
          sig3(sqrt(vcov(main_m)[1, 1]))),
  sprintf("\\newcommand{\\CoefDepTWFE}{%s}",
          sig3(unname(coef(dep_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepTWFE}{%s}",
          sig3(sqrt(vcov(dep_m)[1, 1]))),
  "%",
  "% Within-mother (sibling-FE) depression, >=2-sibling subsample.",
  sprintf("\\newcommand{\\CoefDepSibFE}{%s}",
          sig3(unname(coef(sib_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepSibFE}{%s}",
          sig3(sqrt(vcov(sib_m)["exposure_early_sar_legacy",
                                "exposure_early_sar_legacy"])))
), file.path(here::here("paper"), "numbers.tex"))

log_stage("stage12", "numbers.tex written with CS + TWFE + SibFE macros.")
log_stage("stage12", "done")
