# =====================================================================
# 12_heterogeneity_finalize.R — Heterogeneity + numbers.tex + forest plot.
#
# Heterogeneity dimensions:
#   * By mother education (low/high split at median)
#   * Forest plot across full / male / female / low-edu / high-edu.
#
# An earlier age-window TWFE specification was dropped: the age-window
# dummies are deterministic functions of birth_year * start_year, so
# conditioning on commid x birth-year FEs left them collinear within
# cell and the clustered SEs blew up past 1,000. The critical-period
# pattern is now delivered by the Callaway-Sant'Anna event-study
# figures in stage 09 (paper/figures/event_study_CS_*.pdf).
#
# Outputs:
#   paper/tables/heterogeneity_mother_edu.tex
#   paper/figures/heterogeneity_forest.pdf
#   paper/numbers.tex  — \newcommand for in-text numbers
# =====================================================================

set.seed(20260412)

suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(fixest)
  library(ggplot2)
})

source(here::here("code", "R", "lib", "paths.R"))
source(here::here("code", "R", "lib", "io.R"))
source(here::here("code", "R", "lib", "labels.R"))

log_stage("stage12", "begin")

frame <- read_intermediate("stage06", "analysis_sample")
tables_dir  <- here::here("paper", "tables")
figures_dir <- here::here("paper", "figures")
dir.create(tables_dir,  recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

df <- frame |>
  filter(primary_sample == 1) |>
  mutate(
    sex_f = factor(sex, levels = c(1, 3),
                   labels = c("male", "female")),
    high_medu = as.integer(mother_edu_years >
                             stats::median(mother_edu_years,
                                           na.rm = TRUE))
  )

outcomes <- c("health_index", "cognition_index",
              "depression_index", "bigfive_index")

coef_se <- function(m, var) {
  if (is.null(m) || !var %in% names(coef(m))) return(c(NA, NA))
  c(unname(coef(m)[var]),
    unname(sqrt(vcov(m)[var, var])))
}
fmt <- function(est, se) {
  if (is.na(est)) return("---")
  sprintf("%.3f\n(%.3f)", est, se)
}

# ---------------------------------------------------------------------
# 1. Heterogeneity by mother education.
# ---------------------------------------------------------------------
rows_edu <- lapply(outcomes, function(y) {
  ml <- feols(as.formula(sprintf(paste0(
    "%s ~ exposure_early_sar_legacy | ",
    "commid_birth_legacy + birth_year + source_wave"), y)),
    data = df |> filter(high_medu == 0),
    cluster = ~ commid_birth_legacy)
  mh <- feols(as.formula(sprintf(paste0(
    "%s ~ exposure_early_sar_legacy | ",
    "commid_birth_legacy + birth_year + source_wave"), y)),
    data = df |> filter(high_medu == 1),
    cluster = ~ commid_birth_legacy)
  pl <- coef_se(ml, "exposure_early_sar_legacy")
  ph <- coef_se(mh, "exposure_early_sar_legacy")
  tibble(outcome = y,
         `Low-edu`  = fmt(pl[1], pl[2]),
         `High-edu` = fmt(ph[1], ph[2]))
})
edu_tbl <- bind_rows(rows_edu)

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "\\begin{tabular}{lcc}",
  "\\toprule",
  "Outcome & Low-edu mother & High-edu mother \\\\",
  "\\midrule",
  apply(edu_tbl, 1, function(r) {
    cells <- vapply(r[-1], function(cell)
      paste0("\\makecell{", gsub("\n", "\\\\\\\\", cell), "}"),
      character(1))
    sprintf("%s & %s \\\\", pretty_label(r["outcome"]),
            paste(cells, collapse = " & "))
  }),
  "\\bottomrule",
  "\\end{tabular}"
), file.path(tables_dir, "heterogeneity_mother_edu.tex"))

# Age-window TWFE block removed 2026-04-21. See header comment: the
# age dummies are collinear with the commid x birth-year FE structure,
# so clustered SEs blew up past 1,000. The critical-period pattern is
# delivered by the CS event-study figures from stage 09. A stale copy
# of paper/tables/heterogeneity_age_window.tex must also be removed
# by a one-shot command after this stage runs (see 00_run_all.R).

# ---------------------------------------------------------------------
# 2. Heterogeneity forest plot.
#    Run by-sex + by-mother-edu for each outcome; collect coefs; plot.
# ---------------------------------------------------------------------
forest_rows <- list()
for (y in outcomes) {
  subsets <- list(
    "Full sample" = df,
    "Male"        = df |> filter(sex == 1),
    "Female"      = df |> filter(sex == 3),
    "Low-edu"     = df |> filter(high_medu == 0),
    "High-edu"    = df |> filter(high_medu == 1)
  )
  for (nm in names(subsets)) {
    d <- subsets[[nm]]
    m <- feols(as.formula(sprintf(paste0(
      "%s ~ exposure_early_sar_legacy | ",
      "commid_birth_legacy + birth_year + source_wave"), y)),
      data = d, cluster = ~ commid_birth_legacy)
    p <- coef_se(m, "exposure_early_sar_legacy")
    forest_rows[[paste(y, nm)]] <- tibble(
      outcome = y, subgroup = nm,
      estimate = p[1], se = p[2],
      ci_lo = p[1] - 1.96 * p[2], ci_hi = p[1] + 1.96 * p[2]
    )
  }
}
forest <- bind_rows(forest_rows) |>
  mutate(
    outcome = factor(outcome, levels = outcomes,
                     labels = c("Health index",
                                "Cognition index",
                                "Depression index (higher = better)",
                                "Socioemotional index")),
    subgroup = factor(subgroup, levels = rev(c("Full sample",
                                               "Male", "Female",
                                               "Low-edu", "High-edu")))
  )

# Visual identity mirrors the CS event-study plot in stage 09:
# theme_bw, blue point + errorbar, black dashed zero line, no minor
# gridlines. Consistent palette keeps the reader oriented across the
# paper's three figures.
palette_oi <- c(blue = "#0072B2", vermilion = "#D55E00", black = "#000000")

p_forest <- ggplot(forest,
                   aes(x = estimate, y = subgroup)) +
  geom_vline(xintercept = 0, linetype = "dashed",
             colour = palette_oi["black"], alpha = 0.5) +
  geom_errorbar(aes(xmin = ci_lo, xmax = ci_hi),
                orientation = "y", width = 0.2,
                colour = palette_oi["blue"], linewidth = 0.5) +
  geom_point(size = 2, colour = palette_oi["blue"]) +
  facet_wrap(~ outcome, ncol = 2, scales = "free_x") +
  labs(x = "Effect of early village-midwife exposure (SD)",
       y = NULL) +
  theme_bw(base_size = 11) +
  theme(panel.grid.minor = element_blank())

ggsave(file.path(figures_dir, "heterogeneity_forest.pdf"),
       plot = p_forest, width = 6.5, height = 4.5, units = "in",
       device = cairo_pdf, bg = "white")

# ---------------------------------------------------------------------
# 3. numbers.tex — in-text macros for paper.tex and paper_predoc.tex.
#
# CS macros are pulled from stage 08's persisted att_gt objects so the
# abstract's headline values trace back to the same estimator that
# populates main_results.tex. TWFE baseline macros are recomputed here
# on the same non-migrant frame; sibling-FE macro comes from a fresh
# mother-FE fit on the >=2-sibling subsample to match the robustness
# table. Every macro below must map to a cited \macro somewhere in
# paper/sections; unused macros should be pruned to keep the file honest.
# ---------------------------------------------------------------------
stage08 <- readRDS(here::here("data", "output", "regressions",
                              "stage08_models.rds"))

# TWFE baseline (used as the "TWFE is the wrong lens" benchmark in the
# CS-vs-TWFE comparison paragraphs).
main_m <- feols(health_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year + source_wave,
                data = df, cluster = ~ commid_birth_legacy)
dep_m  <- feols(depression_index ~ exposure_early_sar_legacy |
                  commid_birth_legacy + birth_year + source_wave,
                data = df, cluster = ~ commid_birth_legacy)

# Within-mother (sibling-FE) depression, parallel to stage 10's spec A.
sib_m <- feols(depression_index ~ exposure_early_sar_legacy +
                 birth_order + mother_age_birth |
                 mother_pidlink + birth_year,
               data = df |>
                 filter(!is.na(mother_pidlink)) |>
                 group_by(mother_pidlink) |>
                 filter(n() >= 2) |>
                 mutate(birth_order = rank(birth_year,
                                           ties.method = "first")) |>
                 ungroup(),
               cluster = ~ commid_birth_legacy)

# Mediator sub-sample size (mechanisms.tex footnote).
frame_all <- read_intermediate("stage06", "analysis_sample")
n_med <- frame_all |>
  filter(preceding_sample == 1, !is.na(skilled_attendant)) |>
  nrow()

sig3   <- function(x) sprintf("%.3f", x)
cs_est <- function(y) stage08$cs[[y]]$coef
cs_se  <- function(y) stage08$cs[[y]]$se

writeLines(c(
  "% Auto-generated by code/R/12_heterogeneity_finalize.R",
  "% In-text numerical macros for paper.tex and paper_predoc.tex.",
  "% Regenerate via Rscript code/R/00_run_all.R when the pipeline changes.",
  "%",
  "% Sample-level macros.",
  sprintf("\\newcommand{\\NPrimary}{%s}",
          format(nrow(df), big.mark = ",")),
  sprintf("\\newcommand{\\NVillages}{%s}",
          format(dplyr::n_distinct(df$commid_birth_legacy),
                 big.mark = ",")),
  sprintf("\\newcommand{\\NPrimaryMediator}{%s}",
          format(n_med, big.mark = ",")),
  "%",
  "% Callaway-Sant'Anna dynamic ATT over event-times 0-3 (main specification).",
  sprintf("\\newcommand{\\CoefHealthCS}{%s}", sig3(cs_est("health_index"))),
  sprintf("\\newcommand{\\SEHealthCS}{%s}",   sig3(cs_se("health_index"))),
  sprintf("\\newcommand{\\CoefCogCS}{%s}",    sig3(cs_est("cognition_index"))),
  sprintf("\\newcommand{\\SECogCS}{%s}",      sig3(cs_se("cognition_index"))),
  sprintf("\\newcommand{\\CoefDepCS}{%s}",    sig3(cs_est("depression_index"))),
  sprintf("\\newcommand{\\SEDepCS}{%s}",      sig3(cs_se("depression_index"))),
  sprintf("\\newcommand{\\CoefSocCS}{%s}",    sig3(cs_est("bigfive_index"))),
  sprintf("\\newcommand{\\SESocCS}{%s}",      sig3(cs_se("bigfive_index"))),
  "%",
  "% TWFE comparator (reported as a baseline benchmark).",
  sprintf("\\newcommand{\\CoefHealthTWFE}{%s}",
          sig3(unname(coef(main_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEHealthTWFE}{%s}",
          sig3(sqrt(vcov(main_m)[1, 1]))),
  sprintf("\\newcommand{\\CoefDepTWFE}{%s}",
          sig3(unname(coef(dep_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepTWFE}{%s}",
          sig3(sqrt(vcov(dep_m)[1, 1]))),
  "%",
  "% Within-mother (sibling-FE) depression, >=2-sibling subsample.",
  sprintf("\\newcommand{\\CoefDepSibFE}{%s}",
          sig3(unname(coef(sib_m)["exposure_early_sar_legacy"]))),
  sprintf("\\newcommand{\\SEDepSibFE}{%s}",
          sig3(sqrt(vcov(sib_m)["exposure_early_sar_legacy",
                                "exposure_early_sar_legacy"])))
), file.path(here::here("paper"), "numbers.tex"))

log_stage("stage12", "numbers.tex written with CS + TWFE + SibFE macros.")
log_stage("stage12", "done")
